# Generated for RTOWalaConsultant
import uuid
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='UserRole', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role_name',models.CharField(choices=[('Admin','Admin'),('Staff','Staff')],max_length=20,unique=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Client', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uniq_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('is_active',models.BooleanField(default=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('mobile_number',models.CharField(max_length=15,unique=True)),('email',models.EmailField(blank=True,max_length=254,null=True)),('address',models.CharField(blank=True,max_length=255,null=True))]),
        migrations.CreateModel(name='VehicleDocumentCategory', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100,unique=True)),('is_deleted',models.BooleanField(default=False))]),
        migrations.CreateModel(name='User', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('password',models.CharField(max_length=128,verbose_name='password')),('last_login',models.DateTimeField(blank=True,null=True,verbose_name='last login')),('is_superuser',models.BooleanField(default=False)),('username',models.CharField(error_messages={'unique':'A user with that username already exists.'},help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',max_length=150,unique=True,validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],verbose_name='username')),('first_name',models.CharField(blank=True,max_length=150,verbose_name='first name')),('last_name',models.CharField(blank=True,max_length=150,verbose_name='last name')),('is_staff',models.BooleanField(default=False)),('date_joined',models.DateTimeField(default=django.utils.timezone.now)),('uniq_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('is_active',models.BooleanField(default=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=100)),('mobile_number',models.CharField(max_length=15,unique=True)),('email',models.EmailField(blank=True,max_length=254,null=True)),('address',models.CharField(blank=True,max_length=255,null=True)),('groups',models.ManyToManyField(blank=True,related_name='user_set',related_query_name='user',to='auth.group')),('user_permissions',models.ManyToManyField(blank=True,related_name='user_set',related_query_name='user',to='auth.permission')),('role',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='users',to='api.userrole'))]),
        migrations.CreateModel(name='Vehicle', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uniq_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('is_active',models.BooleanField(default=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('vehicle_number',models.CharField(max_length=20,unique=True)),('vehicle_name',models.CharField(max_length=100)),('vehicle_type',models.CharField(blank=True,choices=[('Bike','Bike'),('Car','Car'),('Truck','Truck'),('Bus','Bus'),('Auto','Auto'),('Other','Other')],max_length=50,null=True)),('fuel_type',models.CharField(blank=True,choices=[('Petrol','Petrol'),('Diesel','Diesel'),('CNG','CNG'),('Electric','Electric'),('Hybrid','Hybrid'),('Other','Other')],max_length=50,null=True)),('client',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='vehicles',to='api.client'))]),
        migrations.CreateModel(name='ErrorLogs', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uniq_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('is_active',models.BooleanField(default=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('msg',models.CharField(max_length=1000)),('path',models.CharField(blank=True,max_length=255,null=True)),('method',models.CharField(blank=True,max_length=20,null=True))]),
        migrations.CreateModel(name='VehicleDocument', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uniq_id',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('is_active',models.BooleanField(default=True)),('is_deleted',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('document_number',models.CharField(blank=True,max_length=100,null=True)),('issue_date',models.DateField(blank=True,null=True)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('provider',models.CharField(blank=True,max_length=100,null=True)),('amount',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('file_path',models.CharField(blank=True,max_length=255,null=True)),('status',models.CharField(choices=[('active','active'),('expiring','expiring'),('expired','expired'),('renewed','renewed')],default='active',max_length=20)),('is_current',models.BooleanField(default=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='created_documents',to=settings.AUTH_USER_MODEL)),('document_category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='documents',to='api.vehicledocumentcategory')),('vehicle',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='documents',to='api.vehicle'))]),
    ]
