# Generated by Django 6.0.4 on 2026-05-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.userrole'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', ' Hybrid'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
